### ISSUE TITLE
error: docs/HISTORY.txt: No such file or directory

### ISSUE THREAD

**Issue by adrigen** [collective/collective.examples.userdata#5]
Installing v 0.4 gives:
Getting distribution for 'collective.examples.userdata'.
error: docs/HISTORY.txt: No such file or directory

on Plone 4.3.2

**Comment by ale-rt** [comment]
In order for this issue to be properly closed we need a 0.4.1 release from the 1.0.x branch.
Can anyone make a release?

**Comment by lentinj** [comment]
Done. How's that look?

**Comment by ale-rt** [comment]
It works:

```
Getting distribution for 'collective.examples.userdata==0.4.1'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got collective.examples.userdata 0.4.1.
```

Thanks! @lentinj

**Comment by khink** [comment]
Alessandro / Johannes: We can give you access in pypi as well, just send me your usernames there.

**Comment by ale-rt** [comment]
@khink Thanks a lot, but I don't think it is needed!
Anyway I am "alert" on PyPI :) 
Ciao!
