### ISSUE TITLE
We lost Plone 4.3 compatible branch

### ISSUE THREAD

**Issue by keul** [collective/collective.examples.userdata#7]
Latest release of this add-on is Plone 5 compatible.

Sadly there's no Plone 4.3 compatible branch and this is **really** bad. Worst: no CHANGES information about that, no major version change...

Is possibile to reanimate a version of this module Plone 4.3 compatible someway?

**Comment by vangheem** [comment]
Can you create a branch? http://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git

**Comment by keul** [comment]
@vangheem: question is how we need to go back in time?

**Comment by vangheem** [comment]
You can create a branch from a specific commit in history. See the stackoverflow link.

**Comment by ebrehault** [comment]
@keul if this PLIP https://github.com/plone/plone.app.users/tree/plip13350-edit-member-schema-ttw-post-z3cform-merge is merged in Plone 5, the plone 5 version of collective.examples.userdata will be pretty much useless (as any customization will be possible using basic GS import), so the Plone 4.3 compliant version is clearly the most valuable thing people might need.

**Comment by thet** [comment]
If true, then this is the 4.x compatible branch: https://github.com/collective/collective.examples.userdata/tree/1.0.x
There is also a new release: https://pypi.python.org/pypi/collective.examples.userdata/0.4.1
